INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Bacon Pizza', 13, 'pizza_bacon.jpg', 'Bacon pizza with mozzarella, oregano, special sauce and house seasoning.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('House-style Pizza', 15, 'pizza_house_style.jpg', 'House-style pizza, with special sauce and all basic ingredients. Cheese of your choice.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Chicken Pizza"', 13, 'pizza_chicken.jpg', 'Chicken pizza with special sauce, mozzarella, chicken  and spices.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Beef Risotto', 20, 'risotto_beef.jpg', 'Spiced beef risotto and a delicious accompanying sauce.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Funghi Risotto', 20, 'risotto_funghi.jpg', 'Funghi risotto made with fine ingredients and the chef`s special touch.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Spaghetti', 15, 'spaghetti.jpg', 'Fresh spaghetti pasta with special sauce and house seasoning.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Fusilli', 15, 'fusilli.jpg', 'Fusili pasta with a chef`s touch and spices.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Penne', 15, 'penne.jpg', 'Fresh penne pasta with special seasoning.');

INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T10:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -22.946779, -43.217753, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T15:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -25.439787, -49.237759, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T16:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T12:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T08:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T14:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T09:00:00Z');

INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 8);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 3);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 7);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 5);